[package]
name = "openlim"
version = "0.1.0"
edition = "2021"

[dependencies]
astm = { path = "../crates/astm" }
async-trait = "0.1.56"
env_logger = "0.9.0"
instruments = { path = "../crates/instruments" }
log = "0.4.17"
thiserror = "1.0.31"
tokio = { version = "1", features = ["full"] }
